apiVersion: v1
kind: ConfigMap
metadata:
  name: data-ingestion-config
  namespace: data-ingestion
data:
  DATASET:           {{ .Values.config.dataset | quote }}
  GCP_PROJECT:       {{ .Values.config.gcpProject | quote }}
  GCP_REGION:        {{ .Values.config.gcpRegion | quote }}
  GCS_BUCKET:        {{ .Values.config.gcsBucket | quote }}
  GCS_RAW_BUCKET:    {{ .Values.config.gcsBucket | quote }}
  GCS_QUALITY_BUCKET: {{ .Values.config.gcsQualityBucket | quote }}
  CYCLES_PER_RUN:    {{ .Values.config.cyclesPerRun | quote }}
  GCS_DATA_KEY:      {{ .Values.config.gcsDataKey | quote }}