apiVersion: batch/v1
kind: CronJob
metadata:
  name: alert-engine
  namespace: alert-naming
  labels:
    app: alert-engine
    component: alert-naming
spec:
  schedule: {{ .Values.alertEngine.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1

  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
          labels:
            app: alert-engine
        spec:
          serviceAccountName: {{ .Values.serviceAccount.name }}
          restartPolicy: OnFailure

          containers:
            - name: alert-engine
              image: "{{ .Values.alertEngine.image.repository }}:{{ .Values.alertEngine.image.tag }}"
              imagePullPolicy: {{ .Values.alertEngine.image.pullPolicy }}
              args: ["src/alert_engine.py"]

              envFrom:
                - configMapRef:
                    name: alert-engine-config

              resources:
                requests:
                  cpu:    {{ .Values.alertEngine.resources.requests.cpu | quote }}
                  memory: {{ .Values.alertEngine.resources.requests.memory | quote }}
                limits:
                  cpu:    {{ .Values.alertEngine.resources.limits.cpu | quote }}
                  memory: {{ .Values.alertEngine.resources.limits.memory | quote }}